import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/organisms/NavBar/NavBar";

const inter = Inter({ subsets: ['latin'] });

const NavLinks = [
  { name: 'Inicio', url: '#' },
  { name: 'Nosotros', url: '#' },
  { name: 'Servicios', url: '#' },
];

const UserLogButtons = [
  { name: 'Registrate', url: '#', variant: 'secondary' as const},
  { name: 'Ingresa', url: '#', variant: 'primary' as const},
]

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NavBar navigationButtons={NavLinks} userButtons={UserLogButtons}/>
      <body className={inter.className}>{children}</body>
    </html>
  );
}